# Generated by Django 2.2 on 2022-11-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('published', models.DateField(blank=True, null=True, verbose_name='Date_of_published')),
                ('created_by', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description about job')),
                ('published', models.DateField(blank=True, null=True, verbose_name='Date_of_published')),
                ('created_by', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
    ]
